name: prototype
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.0
  path_provider: ^2.0.1
  path_provider_foundation: ^2.1.0
  desktop_window: 0.4.0
  intl: ^0.18.0
  
  syncfusion_localizations: ^22.1.34
  syncfusion_flutter_datagrid_export: ^22.1.34-beta
  syncfusion_flutter_calendar: ^22.1.34
  syncfusion_flutter_datepicker: ^22.1.34
  syncfusion_flutter_charts: ^22.1.34
  syncfusion_flutter_gauges: ^22.1.34
  syncfusion_flutter_sliders: ^22.1.34
  syncfusion_flutter_pdf: ^22.1.34
  syncfusion_flutter_barcodes: ^22.1.34
  syncfusion_officechart: ^22.1.34-beta
  syncfusion_flutter_maps: ^22.1.34
  syncfusion_flutter_signaturepad: ^22.1.34
  syncfusion_flutter_pdfviewer: ^22.1.34
  syncfusion_flutter_treemap: ^22.1.34
  get: ^4.6.6

dev_dependencies:
  drift_dev: ^2.12.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

dependency_overrides:
  path: ^1.8.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  